version: '3.4'

services:
  porchgrants:
    image: ${DOCKER_REGISTRY-}porchgrants
    build:
      context: .
      dockerfile: PorchGrants/Dockerfile
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/Data:/var/lib/postgresql/data
